! AS2 — Regional ISP West
! Neighbors: AS1 (10.0.12.1), AS10 (10.0.210.10), AS99 (10.0.299.99)

hostname as2-router
log file /tmp/frr-logs/as2/bgpd.log
log timestamp precision 3

router bgp 2
  bgp router-id 2.2.2.2
  bgp log-neighbor-changes
  no bgp ebgp-requires-policy

  neighbor 10.0.12.1 remote-as 1
  neighbor 10.0.12.1 description AS1-Core
  neighbor 10.0.12.1 timers 10 30

  neighbor 10.0.210.10 remote-as 10
  neighbor 10.0.210.10 description AS10-Victim
  neighbor 10.0.210.10 timers 10 30

  neighbor 10.0.299.99 remote-as 99
  neighbor 10.0.299.99 description AS99-Attacker
  neighbor 10.0.299.99 timers 10 30

  address-family ipv4 unicast
    network 172.16.2.0/24
    neighbor 10.0.12.1   activate
    neighbor 10.0.12.1   soft-reconfiguration inbound
    neighbor 10.0.210.10 activate
    neighbor 10.0.210.10 soft-reconfiguration inbound
    neighbor 10.0.299.99 activate
    neighbor 10.0.299.99 soft-reconfiguration inbound
  exit-address-family