! AS10 — VICTIM — owns 10.10.0.0/16
! Neighbors: AS2 (10.0.210.2)

hostname as10-victim
log file /tmp/frr-logs/as10/bgpd.log
log timestamp precision 3

router bgp 10
  bgp router-id 10.10.10.10
  bgp log-neighbor-changes
  no bgp ebgp-requires-policy

  neighbor 10.0.210.2 remote-as 2
  neighbor 10.0.210.2 description AS2-Upstream
  neighbor 10.0.210.2 timers 10 30

  address-family ipv4 unicast
    network 10.10.0.0/16
    neighbor 10.0.210.2 activate
    neighbor 10.0.210.2 soft-reconfiguration inbound
  exit-address-family