! AS3 — Regional ISP East
! Neighbors: AS1 (10.0.13.1), AS20 (10.0.320.20), AS99 (10.0.399.99)

hostname as3-router
log file /tmp/frr-logs/as3/bgpd.log
log timestamp precision 3

router bgp 3
  bgp router-id 3.3.3.3
  bgp log-neighbor-changes
  no bgp ebgp-requires-policy

  neighbor 10.0.13.1 remote-as 1
  neighbor 10.0.13.1 description AS1-Core
  neighbor 10.0.13.1 timers 10 30

  neighbor 10.0.320.20 remote-as 20
  neighbor 10.0.320.20 description AS20-Legitimate
  neighbor 10.0.320.20 timers 10 30

  neighbor 10.0.399.99 remote-as 99
  neighbor 10.0.399.99 description AS99-Attacker
  neighbor 10.0.399.99 timers 10 30

  address-family ipv4 unicast
    network 172.16.3.0/24
    neighbor 10.0.13.1   activate
    neighbor 10.0.13.1   soft-reconfiguration inbound
    neighbor 10.0.320.20 activate
    neighbor 10.0.320.20 soft-reconfiguration inbound
    neighbor 10.0.399.99 activate
    neighbor 10.0.399.99 soft-reconfiguration inbound
  exit-address-family